main/urls.py
from django.urls import path
from . import views 


app_name = "main"

urlpatterns = [
    #  =----------ADMIN -----------
    path("admin",views.admin_dashboard,name="admin_dashboard"),
    path("departments/",views.departments,name = "admin_departments"),
    path("create-department/",views.create_department,name = "admin_create_department"),
    path("courses/",views.courses,name="admin_courses"),
    path("students/",views.admin_student,name="admin_students"),
    path("teachers/",views.admin_teacher,name="admin_teachers"),
    path("create-course/",views.create_course,name = "admin_create_course"),
    path("assign-course/",views.assign_course,name = "assign_course"),


    # ------------  TEACHER ----------
    path("teacher",views.teacher_dashboard,name="teacher_dashboard"),
    path("teacher/courses/",views.teacher_course_list,name = "teacher_course_list"),
    path("teacher/courses/<slug:slug>",views.teacher_course_detail,name = "teacher_course_detail"),
    path("teacher/assignments/",views.teacher_assignment_list,name = "teacher_assignment_list"),
    path("teacher/assignments/<slug:slug>",views.teacher_assignment_detail,name = "teacher_assignment_detail"),
    path("teacher/assignment-submission/download/<int:id>",views.teacher_assignment_submission_download,name = "teacher_assignment_submission_download"),
    path("teacher/edit-assignment/<slug:slug>",views.teacher_assignment_edit,name = "teacher_assignment_edit"),
    path("teacher/delete-assignment/<slug:slug>",views.teacher_assignment_delete,name = "teacher_assignment_delete"),
    path("teacher/create-assignment/",views.teacher_assignment_create,name = "teacher_assignment_create"),
    path("teacher/submissions/",views.teacher_submissions,name = "teacher_submissions_list"),
    path("teacher/submissions/download/<int:id>",views.teacher_download_submission,name = "teacher_download_submission"),
    path("teacher/submissions/download-all",views.teacher_submissions_download_all,name = "teacher_submissions_download_all"),
    path("teacher/learning-materials/",views.teacher_learning_materials_list,name = "teacher_learning_materials_list"),
    path("teacher/create-learning-materials/",views.teacher_learning_materials_create,name = "teacher_learning_materials_create"), 
    
    
    
    #  -------------- STUDENT -------------
    path("student/",views.student_dashboard,name="student_dashboard"),
    path("student/courses-enroll",views.student_course_enroll,name="student_course_enroll"),
    path("student/courses-enroll-unenroll/<slug:slug>",
         views.student_course_enroll_unenroll_specific,
         name="student_course_enroll_unenroll_specific"
    ),
    path("student/courses",views.student_course_list,name="student_course_list"),
    path("student/course/detail/<slug:slug>",views.student_course_detail,name="student_course_detail"),
    path("student/assignments/",views.student_assignment_list,name="student_assignment_list"),
    path("student/assignments/<slug:slug>",views.student_assignment_detail,name="student_assignment_detail"),
    path("student/learning-materials/",views.student_learning_materials,name="student_learning_materials"),
    path("student/learning-materials/download/<slug:slug>",views.student_learning_material_download,name="student_learning_material_download"),
    path("student/submissions/",views.student_submissions_list,name="student_submissions_list"),
    # path("assignments/",views.assignments,name="assignments"),
    path("courses/",views.courses,name="courses"),   
]

student_mgmt_sys/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("",include("users.urls")),
    path("dashboard/",include("main.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/forms.py
from django import forms
from .models import Department,Assignment,LearningMaterial,Submission,Course
from django.contrib.auth import get_user_model

from django.core.exceptions import ValidationError


User = get_user_model()

class  DepartmentForm(forms.ModelForm):
    class Meta:
        model = Department
        fields = ("name",)
        
    
class CourseForm(forms.ModelForm):
    class Meta:
        model = Course
        fields = "__all__"
        
        widgets = {
            "name":forms.TextInput(attrs={
                "placeholder":"Enter course name here"
            }
            )
            # "teacher":forms.ChoiceField()
        }
        
        
    def __init__(self,*args,**kwargs):
        super().__init__(*args,**kwargs)
        
        self.fields["department"].empty_label = "Select a department"
        self.fields["teacher"].queryset = User.objects.filter(role = "teacher")
        self.fields["teacher"].empty_label = "Select a teacher"
        self.fields["name"].required = True
        self.fields["department"].required = True
        # self.fields["department"].help_text = "Select a department"
                
    def clean(self):
        cleaned_data =  super().clean()
        
        department = self.cleaned_data.get("department")
        # teacher = self.cleaned_data.get("teacher")
        name = self.cleaned_data.get("name")
        
        if Course.objects.filter(name__iexact=name).exists():
            raise ValidationError({"name":"Course already exists"})
        
        if not department:
            raise ValidationError("Course not assigned a department")
                
        return cleaned_data
        
        
        
        
        
        
        
class AssignmentForm(forms.ModelForm):
    class Meta:
        model = Assignment
        fields = ["course","title","description","material","due_date"]
        
        widgets = {
            'due_date': forms.DateTimeInput(attrs={'type': 'datetime-local'})
        }        
        
        
                
    def __init__(self,*args,**kwargs):
        super().__init__(*args,**kwargs)
        # self.fields['due_date'].input_formats = ['%Y-%m-%dT%H:%M']
        
class LearningMaterialsForm(forms.ModelForm):
    class Meta:
        model = LearningMaterial
        fields = ["course","title","description","material"]
        
        # widgets = {
            
        # }
        
        
    def clean(self):
        cleaned_data = super().clean()
        
        course = cleaned_data.get("course")
        title = cleaned_data.get("title")
        description = cleaned_data.get("description")
        material = cleaned_data.get("material")
        
        if not all([course,title,description,material]):
            raise ValidationError("All fields must be filled")        
        
    def __init__(self,*args,**kwargs):
        super().__init__(*args,**kwargs)
        
        self.fields["course"].required = True
        self.fields["title"].required = True
        self.fields["description"].required = True
        self.fields["material"].required = True
        
        
        

main/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponse
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required
from .decorators import allowed_role
from .forms import DepartmentForm,CourseForm,AssignmentForm,LearningMaterialsForm
from django.contrib import messages
from.models import Department,Course,Assignment,LearningMaterial,Submission
from django.http import FileResponse
from django.conf import settings
from django.core.paginator import Paginator
import os

User = get_user_model()

# ------------ADMIN FUNCTIONALITY --------------


@login_required
@allowed_role("admin")
def admin_dashboard(request):       
    return render(request,"main/admin_dashboard.html")

@login_required
@allowed_role("admin")
def departments(request):
    departments = Department.objects.all()

    context = {
        "departments":departments
    }

    for department in departments:
        print(type(department))
        department.num_teachers = department.users.filter(role = "teacher").count() 
        department.num_students = department.users.filter(role = "student").count() 
    return render(request,"main/admin_department_list.html",context)

@login_required
@allowed_role("admin")
def create_department(request):
    print("called to save")
    form = DepartmentForm()
    if request.method == "POST":
        form = DepartmentForm(request.POST)
        if form.is_valid():
            department = form.save(commit=False)
            department.created_by = request.user
            department.save()
            messages.info(request," Course Created Successfully")
            
    return render(request,"main/admin_create_department.html",{"form":form})

@login_required
@allowed_role("admin")
def courses(request):
    courses = Course.objects.all()
    
    context = {
        "courses":courses
    }
    return render(request,"main/admin_course_list.html",context)


@login_required
@allowed_role("admin")
def admin_student(request):
    students = User.objects.filter(role = "student")
    
    context = {
        "students":students
    }
    
    return render(request,"main/admin_student_list.html",context)

@login_required
@allowed_role("admin")
def admin_teacher(request):
    teachers = User.objects.filter(role = "teacher")
    
    context = {
        "teachers":teachers
    }
    
    return render(request,"main/admin_teacher_list.html",context)


@login_required
@allowed_role("admin")
def create_course(request):
    teachers = User.objects.filter(role = "teacher")
    form = CourseForm()
    # print(vars(form))
    if request.method == "POST":
        
        form = CourseForm(request.POST)
        if form.is_valid():
            name = form.cleaned_data.get("name")
            department  = form.cleaned_data.get("department")
            teacher = form.cleaned_data.get("teacher")
            
            print(f"name:{name},depaerment:{department},teacher:{teacher}")
            
            
            if teacher:
                if teacher.department.name.lower() == department.name.lower():
                    Course.objects.create(
                        name = name,
                        department = department,
                        created_by = request.user,
                        teacher = teacher                            
                    )
                    messages.info(request,"Course Created successfuly")
                else:
                    form.add_error(None,f"Teacher is not in {department} department")
                
            else:
                Course.objects.create(
                    name = name,
                    department = department,
                    created_by = request.user,
                )      
                
        else:
            print(form.errors)   
                   
                       
        #     if name and not (department or course):
        #         course = Course.objects.create(name= name,created_by = request.user)
        #         print("1 set ")

        #     elif name and department and not department:
        #         department = Department.objects.get(name = department)
        #         course = Course.objects.create(
        #             name= name,
        #             department = department,
        #             created_by = request.user
        #         )
        #         print("all 2 set")

        #     elif all([name,department,teacher]):
        #         teacher = User.objects.get(username = teacher)
        #         if teacher.department == department:
                    
        #             print("teacher is ",teacher)
        #             department = Department.objects.get(name = department)
                    
        #             course = Course.objects.create(
        #                 name = name,
        #                 teacher = teacher,
        #                 department = department,
        #                 created_by = request.user
        #             )
                    
        #         else:
        #             form.add_error(None,"Teacher is not is not in associated department")                    
            
        #     # course = form.save(commit=False)
        #     # course.created_by = request.user
        #     # course.save()
        # else:
        #     print(form.errors)
        
    context = {
        "form":form,
        "teachers":teachers
        }
    return render(request,"main/admin_create_course.html",context)

@login_required
@allowed_role("admin")
def assign_course(request):
    if request.method == "POST":
        # department_id = request.POST.get("department") if request.POST["department"] else 0
        course_id = request.POST.get("course") if request.POST["course"] else 0
        teacher_id = request.POST.get("teacher") if request.POST["teacher"] else 0
        
        course = Course.objects.filter(id = course_id).first()
        teacher = User.objects.filter(id = teacher_id,role = "teacher").first()
        
        if teacher and course:
            if course.department == teacher.department:
                course.teacher = teacher
                course.save() 
            else:
                messages.error(request,f"Teacher not in {course.department.name} department")
        
        
        # if not department_id :
        #     department_id = 0
        # if not course_id:
        #     course_id = 0
        # if not teacher_id:
        #     teacher_id = 0
        
        
        # print(f"Dept. {department_id},course {course_id}, teacher {teacher_id}")
        
        # print("This runs")
        # department = Department.objects.filter(id = department_id).first()
        # print(department)
        # course = Course.objects.filter(id = course_id).first()
        # print(course)
        # teacher = User.objects.filter(role = "teacher", id = teacher_id).first()
        # print(teacher)
        
        # if department:
            
        #     if course.department:
        #         if course.department == department:
        #             if not course.teacher:
        #                 if teacher.department == department:
        #                     course.teacher = teacher
        #                     course.save()
        #                 else:
        #                     messages.error(request,f"This teacher is not in  {department} department" )
        #             else:
        #                 messages.error(request,"This course already has a teacher")

        #         else:
        #             messages.error(request,f"This course is not under the chosen department")
        #     else:
        #         messages.error(request, "Course has no Department assigned to it ")
        # else:
        #     if course.department:
        #         messages.error(request,"Course has no department")
                
        #         if course.department == teacher.department:
        #             course.teacher = teacher
        #             course.save()
        #         else:
        #             messages.error(request,f"This teacher is not in department associated with course")
                    
        #     else:
        #         messages.error(request, "Course has no department")
                
    departments = Department.objects.all()
    courses = Course.objects.all()
    teachers = User.objects.filter(role = "teacher")
      
      
    context = {
        "departments":departments,
        "courses":courses,
        "teachers":teachers
    }
    return render(request,"main/admin_assign_course.html",context)




#-------------TEACHER FUNCTIONALITY ---------------- 


@login_required
@allowed_role("teacher")
def teacher_dashboard(request):
    now = timezone.now()
    courses = Course.objects.filter(teacher = request.user)
    print(courses)
    active_assignments = Assignment.objects.filter(
        course__teacher = request.user,
        due_date__gte = now
    )
    
    assignments_given = Assignment.objects.filter(
        course__teacher = request.user
    )
    
    courses_with_assignments = courses.filter(
        assignments__isnull = False
    ).distinct()
    
    print(courses_with_assignments)

    submissions_for_assignments = Submission.objects.filter(
        assignment__in = assignments_given
    )
    
    print("submissions is ",submissions_for_assignments)
        
    # courses_with_assignments = courses.filter(assignments__isnull = False)
    # assignments_given = Assignment.objects.filter(course__in = courses)
    # submissions_for_assignments = Submission.objects.filter(assignment__in=assignments_given)
    
    
    context ={
        "total_courses":courses.count(),
        "total_active_assignments":active_assignments.count(),
        "total_courses_with_assignments":courses_with_assignments.count(),
        "total_assignments_given":assignments_given.count(),

main/templates/main/admin_department.html
{% extends 'main_base.html' %}
{% load static %}
{% block extra_styles %}<link rel="stylesheet" href="{% static 'main/css/departments.css' %}">
{% endblock extra_styles %}
{% block body %}
  <div class="container">
    <h2>Departments</h2>
    <a href="{% url 'main:create_department'%}" class="add-btn">+ Add Department</a>

    <table>
      <thead>
        <tr>
          <th>ID</th>
          <th>Department Name</th>
          <th>Created By</th>
          <!-- <th>Updated At</th> -->
          <th>Actions</th> 
        </tr>
      </thead>
      <tbody id="departmentList">
        {%for department in departments %}
        <tr>
            <td>{{department.id}}</td>
            <td>{{department.name}}</td>
            <td>{{department.created_by}}</td>
            <!-- <td>department.name</td> -->
        </tr>
        {% endfor %}
        <!-- Dynamic rows will come from backend -->
      </tbody>
    </table>
  </div>

  <script>
    // Later you'll populate this table dynamically with Django data
    // For now, the structure is ready to accept data via backend
  </script>
{% endblock body %}

main/templates/main/admin_student_list.html
{% extends 'main_base.html' %}
{% load static %}
{% block extra_styles %}<link rel="stylesheet" href="{% static 'main/css/departments.css' %}">
{% endblock extra_styles %}
{% block body %}
  <div class="container">
    <h2>Students</h2>
    <!-- <a href="{% url 'main:admin_create_department'%}" class="add-btn">+ Add Department</a> -->

    <table>
      <thead>
        <tr>
          <th>ID</th>
          <th>Student Name</th>
          <th>School_ID</th>
          <!-- <th>Updated At</th> -->
          <th>Actions</th> 
        </tr>
      </thead>
      <tbody id="departmentList">
        {%for student in students %}
        <tr>
            <td>{{student.id}}</td>
            <td>{{student.username}}</td>
            <td>{{student.school_id}}</td>
            <td>{{student.}}</td>
            <!-- <td>department.name</td> -->
        </tr>
        {% endfor %}
        <!-- Dynamic rows will come from backend -->
      </tbody>
    </table>
  </div>

  <script>
    // Later you'll populate this table dynamically with Django data
    // For now, the structure is ready to accept data via backend
  </script>
{% endblock body %}

main/templates/main/student_assignments_list.html
{% extends 'student_base.html' %}
{% load static %}
{% block extra_styles %} <link rel="stylesheet" href="{% static 'main/css/student_assignments_list.css' %}">
{% endblock extra_styles %}


{% block body %}
  <div class="assignments-container">
    <h1>All Assignments</h1>

    <div class="filters">
      <label for="course-filter">Course:</label>
      <select id="course-filter">
        <option value="all">All</option>
        <option value="cse101">CSE101 - Intro to Programming</option>
        <option value="cse102">CSE102 - Data Structures</option>
        <option value="cse201">CSE201 - Computer Networks</option>
      </select>

      <label for="status-filter">Status:</label>
      <select id="status-filter">
        <option value="all">All</option>
        <option value="submitted">Submitted</option>
        <option value="pending">Pending</option>
        <option value="overdue">Overdue</option>
      </select>
    </div>

    {% for assignment in assignments %}

    <div class="assignment-card">
      <h3>{{assignment.title}}</h3>
      <p><strong>Course:</strong> {{assignment.course.name}}</p>
      <p><strong>Due Date:</strong> {{assignment.due_date}}</p>
      {% if assignment in submitted_assignments %}
      <p><strong>Status: Submitted </strong> </p>
      {% else %}
      <p><strong>Status: Pending </strong> </p>
      {% endif %}
      {% if assignment.due_date < now %}
      <p class="due-date"> Time is due </p>
      {% elif assignment in submitted_assignments  %}
      <a href="{% url 'main:student_assignment_detail' assignment.slug %}"> View/Update</a>
      {% else %}
      <a href="{% url 'main:student_assignment_detail' assignment.slug %}"> View/submit</a>
      {% endif %}
    </div>
    {% endfor %}
    <!-- <div class="assignment-card">
      <h3>Assignment 2: Loops Practice</h3>
      <p><strong>Course:</strong> CSE101</p>
      <p><strong>Due Date:</strong> 22 Nov 2025</p>
      <p><strong>Status:</strong> Submitted</p>
      <button>View Submission</button>
    </div>

    <div class="assignment-card">
      <h3>Assignment 1: Arrays & Lists</h3>
      <p><strong>Course:</strong> CSE102</p>
      <p><strong>Due Date:</strong> 20 Nov 2025</p>
      <p><strong>Status:</strong> Overdue</p>
      <button>View / Submit</button>
    </div>

    <div class="assignment-card">
      <h3>Assignment 1: Network Layers</h3>
      <p><strong>Course:</strong> CSE201</p>
      <p><strong>Due Date:</strong> 18 Nov 2025</p>
      <p><strong>Status:</strong> Pending</p>
      <button>View / Submit</button>
    </div> -->

    <p class="no-results" style="display: none;">No assignments found for the selected filters.</p>
  </div>
{% endblock body %}

main/templates/main/student_course_list.html
{% extends 'student_base.html' %}
{% load static %}
{% block extra_styles %} <link rel="stylesheet" href="{% static 'main/css/student_course_list.css' %}">
{% endblock extra_styles %}

{% block body %}

  <h1 class="page-title">My Enrolled Courses</h1>

  <div class="course-container">
    <!-- Example Enrolled Course -->
    {% for course in courses %}
      <div class="course-card">
        <h3>{{course.name}}</h3>
        <p><strong>Instructor:</strong> {{course.teacher.username}}</p>
        <p><strong>Duration:</strong> 12 weeks</p>
        <!-- <p><strong>Status:</strong> Ongoing</p> -->
        <!-- <p>Learn about communication protocols, topology, and network devices.</p> -->
        <a href="{% url 'main:student_course_detail' course.slug %}" class="view-btn">View Course</a>
      </div>
    {% endfor %}
    <!-- <div class="course-card">
      <h3>Database Systems</h3>
      <p><strong>Instructor:</strong> Dr. Ama Adjei</p>
      <p><strong>Duration:</strong> 11 weeks</p>
      <p><strong>Status:</strong> Ongoing</p>
      <p>Understand relational models, SQL queries, and data normalization.</p>
      <a href="#" class="view-btn">View Course</a>
    </div>

    <div class="course-card">
      <h3>Web Development with Django</h3>
      <p><strong>Instructor:</strong> Mr. Samuel Boateng</p>
      <p><strong>Duration:</strong> 14 weeks</p>
      <p><strong>Status:</strong> Ongoing</p>
      <p>Develop scalable and secure web applications using Django framework.</p>
      <a href="#" class="view-btn">View Course</a>
    </div>
  </div> -->

  <!-- If no enrolled courses exist -->
  <!-- <p class="no-course">You have not enrolled in any courses yet.</p> -->

{% endblock body %}

main/templates/main/student_dashboard.html
{% extends 'student_base.html' %}
{% load static }
{% block body %}

  <!-- Main -->
    <div class="top-bar">
      <h1>Welcome Back, Student!</h1>
      <div class="profile">
        <img src="{{user.image.url}}" alt="Student">
        <span>Jane Doe</span>
      </div>
    </div>

    <section class="dashboard-content">
      <div class="card">
        <h2>My Courses</h2>
        <h5> No. enrolled courses: <span>{{total_courses|length }}</span> </h5>
        <ul>
          <!-- <li>Web Programming</li>
          <li>Signals & Systems</li>
          <li>Embedded Systems</li>
          <li>Software Engineering</li> -->
        </ul>
        <a href="{% url 'main:student_course_list' %}" class="action-btn">View All Courses</a>
      </div>

      <div class="card">
        <h3>Active Assignments</h3>
        <h5> Active assignments : <span>{{active_assignments|length }}</span> </h5>
        <!-- <ul>
          <li>Web Programming – <strong>Due Nov 10</strong></li> -->
          <!-- <li>Signals & Systems – <strong>Due Nov 8</strong></li> -->
        <!-- </ul> -->
        <a href="{% url 'main:student_assignment_list' %}" class="action-btn">View Assignments</a>
      </div>

      <div class="card">
        <h3>Learning Materials</h3>
        <h5> Current Learning materials : <span>{{learning_materials|length }}</span> </h5>

        <!-- <ul>
          <li>Lecture Notes: Signal Decomposition</li>
          <li>Slides: Software Design Principles</li>
          <!-- <li>Lab Manual: Arduino Setup Guide</li> -->
        <!-- </ul> --> 
        <a href="{% url 'main:student_learning_materials' %}" class="action-btn">Access Materials</a>
      </div>
    </section>

    <section class="enroll-section">
      <a href="{% url 'main:student_course_enroll' %}" class="enroll-btn">+ Enroll for a New Course</a>
    </section>

    <section class="table-container">
      <h2>Recent Assignments</h2>
      <table>
        <thead>
          <tr>
            <th>Course</th>
            <th>Assignment</th>
            <th>Due Date</th>
            <th>Status</th>
            <th>Action</th>
          </tr>
        </thead>
        <tbody>
        {% for assignment in active_assignments %}
          <tr>
            <td> {{assignment.course}} </td>
            <td> {{assignment.title}}</td>
            <td>{{assignment.due_date}}</td>]
            {% if assignment in submitted_assignments %}
            <td>Submitted</td>
            {% else %}
            <td>Pending</td>
            {% endif %}
            <td><a href="{% url 'main:student_assignment_detail' assignment.slug %}" class="action-btn-table">Submit</a></td>
          </tr>
        {% endfor %}

        </tbody>
      </table>
    </section>

  {% endblock body %}

main/templates/main/teacher_assignment_details.html
{% extends 'teacher_base.html' %}
{% load static %}
{% block extra_styles %}<link rel="stylesheet" href="{% static 'main/css/teacher_assignment_details.css' %}">
{% endblock extra_styles %}
{% block body %}
    <div class="assignment-info">
      <h1>{{assignment}} - {{assignment.course.name}} </h1>
      <p><strong>Due Date:</strong> October 30, 2025</p>
      <p><strong>Total Submissions:</strong> 24</p>
    </div>

    <div class="submissions-table">
      <h2>Student Submissions</h2>
      <table>
        <thead>
          <tr>
            <th>Student Name</th>
            <th>Student ID</th>
            <th>Submitted On</th>
            <th>File</th>
          </tr>
        </thead>
        <tbody>
          {% for submission in submissions %}
          <tr>
            <td>{{submission.student.username}}</td>
            <td>{{submission.student.school_id}}</td>
            <td>{{submission.submitted_on}}</td>
            <td><a href="{% url 'main:teacher_assignment_submission_download' submission.id %}" class="btn btn-download">Download</a></td>
          </tr>
          {% empty %}
          <li>
            <span>No submissions yet </span>
          </li>          
          {% endfor %}
        </tbody>
      </table>
    </div>
{% endblock body %}

main/templates/main/teacher_learning_materials_list.html
{% extends 'teacher_base.html' %}
{% load static %}
{% block extra_styles %}<link rel="stylesheet" href="{% static 'main/css/teacher_learning_materials_list.css' %}">
{% endblock extra_styles %}
{% block body %}
  <div class="wrapper">
    <div class="header">
      <h1>Learning Materials</h1>
      <div class="controls">
        <select>
          <option value="">Filter by Course</option>
          <option value="1">Mathematics</option>
          <option value="2">English Language</option>
        </select>
        <a href="{% url 'main:teacher_learning_materials_create' %}" class="add-btn">+ Add Material</a>
      </div>
    </div>

    <div class="materials">
      {% for material in materials %}
      <div class="material-card">
        <h3>{{material.title}}</h3>
        <p>{{material.description}}</p>
        <div class="meta">Course: {{material.course}} | Uploaded: {{material.created_at}}</div>
        <div class="btns">
          <button class="view">View</button>
          <button class="delete">Delete</button>
        </div>
      </div>
      {% endfor %}

      <!-- <div class="material-card">
        <h3>Essay Techniques</h3>
        <p>How to write strong essays and arguments.</p>
        <div class="meta">Course: English Language | Uploaded: 2025-10-25</div>
        <div class="btns">
          <button class="view">View</button>
          <button class="delete">Delete</button>
        </div> -->
      </div>
    </div>
  </div>
</body>
{% endblock body %}

main/templates/main/teacher_submissions_list.html
{% extends 'teacher_base.html' %}
{% load static %}
{% block extra_styles %}<link rel="stylesheet" href="{% static 'main/css/teacher_submissions_list.css' %}">
{% endblock extra_styles %}
{% block body %}
  <div class="page-header">
    <h1>Student Submissions</h1>
    <div class="filters">
      <select name="course" id="course">
        <option value="">Filter by Course</option>
        <option value="1">Mathematics</option>
        <option value="2">English Language</option>
        <option value="3">Integrated Science</option>
      </select>

      <select name="assignment" id="assignment">
        <option value="">Filter by Assignment</option>
        <option value="1">Assignment 1 - Algebra</option>
        <option value="2">Assignment 2 - Grammar</option>
      </select>

      <a class="download-btn" href="{% url 'main:teacher_submissions_download_all' %}">Download all</a>
      <!-- <button class="download-btn">Download All</button> -->
    </div>
  </div>

  <div class="table-container">
    <table>
      <thead>
        <tr>
          <th>Student Name</th>
          <th>Course</th>
          <th>Assignment</th>
          <th>Submitted On</th>
          <th>File</th>
          <th>Action</th>
        </tr>
      </thead>
      <tbody>
        {% for submission in submissions %}
        <tr>
          <td>{{submission.student}}</td>
          <td>{{submission.assignment.course.name}}</td>
          <td>{{submission.assignment.title}}</td>
          <td>{{submission.submitted_on}}</td>
          <td><a href="{% url 'main:teacher_download_submission' submission.id %}" class="action-btn">View File</a></td>
          <td><button class="action-btn">Grade</button></td>
        </tr>
          {% empty %}
          <li>
            <span>No materials yet </span>
          </li>          
        {% endfor %}
        <!-- <tr>
          <td>Akua Nyarko</td>
          <td>English Language</td>
          <td>Essay Writing</td>
          <td>2025-10-26</td>
          <td><a href="#" class="action-btn">View File</a></td>
          <td><button class="action-btn">Grade</button></td>
        </tr> -->
      </tbody>
    </table>
  </div>
{% endblock body %}